---
title: "All in one permutattion tool one sided chr16"
output: html_notebook
---


```{r}
setwd("C:/Users/Wietse/Desktop/Stage/Current work file")
library(tidyverse)
library(WGCNA)
library(AnnotationDbi)
library(igraph)
library(gdata)

options(stringsAsFactors = TRUE)
expression_data <- read.csv("expression_matrix.csv", header = FALSE)
column_data <- read.csv("columns_metadata.csv")
row_data <- read.csv("rows_metadata.csv")

expression_data <- expression_data[-1];
rownames(expression_data) <- row_data[,3]
expression_data$entrez_id <- row_data[,5]
expression_data <- expression_data[!is.na(expression_data$entrez_id), ]

row_data <- row_data[!is.na(row_data$entrez_id), ]

expression_data<- expression_data[ , -which(names(expression_data) %in% c("entrez_id"))]

expression_data.t <- t(expression_data)
expression_data.t <- as.data.frame(expression_data.t)

rownames(expression_data.t) <- paste0("S", 1:nrow(expression_data.t))
rownames(column_data) <- paste0("S", 1:nrow(column_data))

expression_data.t<- log2(expression_data.t + 1)
```

```{r}


#from_options <- c("1","6","10","27","45","59","64","68","74","80","81","82","88","99","103","109","114","122","124")
#to_options <- c("5","9","26", "44", "58", "63", "67", "73", "79", "80", "81","87", "98", "102","108","113","121","123","132")
#expression_data.t <- expression_data.t[column_data$structure_acronym %in% c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
#column_data <- column_data[column_data$structure_acronym %in% c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]


#from_options <- c("1","2","3","7","9","10","12","14","15","17","21","23","25")
#to_options <- c("1","2","6", "8", "9", "11", "13", "14", "16", "20","22","24","26")

#expression_data.t <- expression_data.t[column_data$structure_acronym %in% c("MD","CBC"),]
#column_data <- column_data[column_data$structure_acronym %in% c("MD","CBC"),]

gsg <- goodSamplesGenes(expression_data.t)
expression_data.t = expression_data.t[gsg$goodSamples, gsg$goodGenes]
row_data = row_data[gsg$goodGenes,]


  
  require(org.Hs.eg.db)

    uniKeys <- keys(org.Hs.eg.db, keytype="MAP")
    cols <- c("ENSEMBL", "ENTREZID")

    gene_locations <- select(org.Hs.eg.db, keys=uniKeys, columns=cols, keytype="MAP")

    probes <- rownames(t(expression_data.t))
    probes2annot = match(probes, gene_locations$ENSEMBL)
    locations = gene_locations$MAP[probes2annot]
    row_data$location <- locations
  
  
  rownames(row_data) <- paste0(1:nrow(row_data))
  
  rownames(column_data) <- paste0(1:nrow(column_data))
  
```

```{r}
CNV_genes <- c(
"ENSG00000013364", "ENSG00000072864", "ENSG00000079616",
"ENSG00000085721", "ENSG00000090238", "ENSG00000091262",
"ENSG00000102879", "ENSG00000102882", "ENSG00000102886",
"ENSG00000103222", "ENSG00000103485", "ENSG00000103495",
"ENSG00000103502", "ENSG00000103512", "ENSG00000133392",
"ENSG00000133393", "ENSG00000149922", "ENSG00000149923",
"ENSG00000149925", "ENSG00000149926", "ENSG00000149929",
"ENSG00000149930", "ENSG00000149932", "ENSG00000156968",
"ENSG00000157045", "ENSG00000166780", "ENSG00000166783",
"ENSG00000167194", "ENSG00000167371", "ENSG00000169592",
"ENSG00000174938", "ENSG00000174939", "ENSG00000174943",
"ENSG00000183336", "ENSG00000183793", "ENSG00000197471",
"ENSG00000254852"
)

gene_names <- subset(row_data, ensembl_gene_id %in% CNV_genes)
expression_data_CNV_genes <- as.data.frame(t(t(expression_data.t)[ which(row_data$ensembl_gene_id %in% CNV_genes),]))

expression_data.full <- as.data.frame(t(t(expression_data.t)[ -which(row_data$ensembl_gene_id %in% CNV_genes),]))
row_data.full <- row_data[ -which(row_data$ensembl_gene_id %in% CNV_genes),]
column_data.full <- column_data

```

```{r}


CNV_overview <- list(matrix(c(0), nrow = 1, ncol = 13),matrix(c(0), nrow = 1, ncol = 17),matrix(c(0), nrow = 1, ncol = 11), matrix(c(0), nrow = 1, ncol = 11))

a<-1

for (a in 1:4) {
  
 if(a == 1){
  expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in% c("V1C","ITC","IPC","A1C","STC"),]
  column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("V1C","ITC","IPC","A1C","STC"),]
 
  from_options <- c(1,3,17,31,45,49,53,58,63,64,66,71,82,86,91)
  to_options <- c(2,16,30,44,48,52,57,62,63,65,70,81,85,90,94)
  }
 if(a == 2){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
  
    from_options <- c(1,6,10,27,45,59,64,68,74,80,81,82,88,99,103,109,114,122,124)
    to_options <- c(5,9,26,44,58,63,67,73,79,80,81,87,98,102,108,113,121,123,132)
 }
  if(a == 3){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("STR","HIP","AMY"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("STR","HIP","AMY"),]
  
    from_options <- c(1,3,5,14,23,30,33,35,38,41,44,51,54)
    to_options <- c(2,4,13,22,29,32,34,37,40,43,50,53,54)
  }
  if(a == 4){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("MD","CBC"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("MD","CBC"),]
  
    from_options <- c(1,2,3,7,9,10,12,14,15,17,21,23,25)
    to_options <- c(1,2,6,8,9,11,13,14,16,20,22,24,26)
  }
 b<-1 

for (b in 1:(length(from_options)-2)) {
    from<- from_options[b]
    j = b + 2
    to <- to_options[j]
    
    expression_data.t<- expression_data.t1[from:to, ]
    column_data <- column_data1[from:to, ]

    
    annot <- gene_names
    rownames(annot) <- paste0(1:nrow(annot))
    annot <- rowid_to_column(annot)
    nodes <- annot[,-c(2:4, 6:7)]
    
    adjacency <- adjacency(expression_data.t, type = "signed")

    TOM_per <- TOMsimilarity(adjacency, TOMType = "signed")
    rownames(TOM_per) = rownames(adjacency)
    TOM_per <- t(TOM_per)
    rownames(TOM_per) = rownames(adjacency)

    vis = exportNetworkToVisANT(TOM_per,
    file = NULL,
    weighted = TRUE,
    threshold = 0.25,
    probeToGene = data.frame(annot$ensembl_gene_id, annot$gene_symbol))
    vis <- vis[,-c(3:4)] 

    edges <- vis %>% 
    left_join(nodes, by = c("from" = "gene_symbol")) %>% 
    dplyr::rename(from1 = rowid)
    edges <- edges %>% 
    left_join(nodes, by = c("to" = "gene_symbol")) %>% 
    dplyr::rename(to1 = rowid)
    edges <- dplyr::select(edges, from1, to1, weight)

    graph <- graph_from_data_frame(d = edges, vertices = nodes, directed = FALSE)

    degree_centrality <- centr_degree(graph, normalized = FALSE)



CNV_overview[[a]][1,b] <- centralize(degree_centrality[["res"]], theoretical.max = degree_centrality[["theoretical_max"]], normalized = TRUE)
}
}
```

```{r}
#TO DO:
#add outlier gsg check within the loops
#remove seed genes from permutation options #DONE
#add brain regions 3&4 #DONE
#do two sided and other sided analysis

run_overview <- list(matrix(c(0), nrow = 200, ncol = 13), matrix(c(0), nrow = 200, ncol = 17), matrix(c(0), nrow = 200, ncol = 11),matrix(c(0), nrow = 200, ncol = 11) )

del_genes <- c("ENSG00000102886","ENSG00000149925", "ENSG00000102882", "ENSG00000149929", "ENSG00000079616","ENSG00000174939", "ENSG00000183336", "ENSG00000103502", "ENSG00000102879","ENSG00000149926", "ENSG00000103495", "ENSG00000149923", "ENSG00000090238", "ENSG00000103485", "ENSG00000149930", "ENSG00000174938", "ENSG00000149922", "ENSG00000167371", "ENSG00000149932", "ENSG00000174943", "ENSG00000013364", "ENSG00000197471", "ENSG00000169592",  "ENSG00000167194")




a<-1
d<-1



for (a in 1:4) {
  
  if(a == 1){
  expression_data.t1 <- expression_data.full[column_data.full$structure_acronym %in% c("V1C","ITC","IPC","A1C","STC"),]
  column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("V1C","ITC","IPC","A1C","STC"),]
 
  from_options <- c(1,3,17,31,45,49,53,58,63,64,66,71,82,86,91)
  to_options <- c(2,16,30,44,48,52,57,62,63,65,70,81,85,90,94)
  }
 if(a == 2){
    expression_data.t1 <- expression_data.full[column_data.full$structure_acronym %in%  c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
  
    from_options <- c(1,6,10,27,45,59,64,68,74,80,81,82,88,99,103,109,114,122,124)
    to_options <- c(5,9,26,44,58,63,67,73,79,80,81,87,98,102,108,113,121,123,132)
 }
  if(a == 3){
    expression_data.t1 <- expression_data.full[column_data.full$structure_acronym %in%  c("STR","HIP","AMY"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("STR","HIP","AMY"),]
  
    from_options <- c(1,3,5,14,23,30,33,35,38,41,44,51,54)
    to_options <- c(2,4,13,22,29,32,34,37,40,43,50,53,54)
  }
  if(a == 4){
    expression_data.t1 <- expression_data.full[column_data.full$structure_acronym %in%  c("MD","CBC"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("MD","CBC"),]
  
    from_options <- c(1,2,3,7,9,10,12,14,15,17,21,23,25)
    to_options <- c(1,2,6,8,9,11,13,14,16,20,22,24,26)
  }
  
 b<-1 
  
for (b in 1:(length(from_options)-2)) {
    from<- from_options[b]
    j = b + 2
    to <- to_options[j]
    
    expression_data.t<- expression_data.t1[from:to, ]
    column_data <- column_data1[from:to, ]
    
    
   
    ########################################################## Make chr16 specific
    row_data <- row_data.full[order(row_data.full$location),]

    rownames(row_data) <- paste0( 1:nrow(row_data))
    row_data <- row_data[-c(1:4860, 5319:nrow(row_data)), ] 

    expression_data.t <- as.data.frame(t(subset(t(expression_data.t), rownames(t(expression_data.t)) %in% row_data$ensembl_gene_id)))
    nums <- 1:(as.numeric(nrow(row_data)-14))
    #######################################################################
    
  c <- 1  
for(c in 1:200){
 
  selection_start <- sample(nums, 1)
  select_end <- selection_start +13

  
  rows2 <- row_data[selection_start:select_end,]
  
  rows2annot <- match(rows2$ensembl_gene_id, names(expression_data.t))

  expression_data_random <- rownames_to_column(expression_data.t[rows2annot])
  
  expression_data_del_genes <-  subset(t(expression_data.t), names(expression_data.t) %in% del_genes)
  expression_data_del_genes <- rownames_to_column(as.data.frame(t(expression_data_del_genes)))

  expression_data <- left_join(as.data.frame(expression_data_random), as.data.frame(expression_data_del_genes))

  expression_data <- expression_data[,-1]

  annot <- subset(row_data, row_data$ensembl_gene_id %in% names(expression_data))
  rownames(annot) <- paste0(1:nrow(annot))
  annot <- rowid_to_column(annot)
  nodes <- annot[,-c(2:4, 6:7)]
  
  expression_data <- expression_data[,-1]
  
  adjacency <- adjacency(expression_data, type = "signed")

  TOM_per <- TOMsimilarity(adjacency, TOMType = "signed")
  rownames(TOM_per) = rownames(adjacency)
  TOM_per <- t(TOM_per)
  rownames(TOM_per) = rownames(adjacency)

  vis = exportNetworkToVisANT(TOM_per,
  file = NULL,
  weighted = TRUE,
  threshold = 0.25,
  probeToGene = data.frame(annot$ensembl_gene_id, annot$gene_symbol))
  vis <- vis[,-c(3:4)] 

edges <- vis %>% 
  left_join(nodes, by = c("from" = "gene_symbol")) %>% 
  dplyr::rename(from1 = rowid)
edges <- edges %>% 
  left_join(nodes, by = c("to" = "gene_symbol")) %>% 
  dplyr::rename(to1 = rowid)
edges <- dplyr::select(edges, from1, to1, weight)

graph <- graph_from_data_frame(d = edges, vertices = nodes, directed = FALSE)

degree_centrality <- centr_degree(graph, normalized = FALSE)




run_overview[[a]][c,b] <- centralize(degree_centrality[["res"]], theoretical.max = degree_centrality[["theoretical_max"]], normalized = TRUE)
}
}
}  

```

```{r}
heatmap <- matrix(nrow = 4, ncol = 17)

heatmap[,]=0.5

e <- 1
for (e in 1:13) {
temp <- run_overview[[1]][,e]
plot(density(run_overview[[1]][,e]), main = length(temp[temp>CNV_overview[[1]][e]])/200)
abline(v = CNV_overview[[1]][e], col = "red")
heatmap[1,e] <- 1-(length(temp[temp>CNV_overview[[1]][e]])/200)
}  
 
```

```{r}
e <- 1
for (e in 1:17) {
temp <- run_overview[[2]][,e]
plot(density(run_overview[[2]][,e]), main = length(temp[temp>CNV_overview[[2]][e]])/200)
abline(v = CNV_overview[[2]][e], col = "red")
heatmap[2,e] <- 1-(length(temp[temp>CNV_overview[[2]][e]])/200)
}  

```

```{r}
e <- 1
for (e in 1:11) {
temp <- run_overview[[3]][,e]
plot(density(run_overview[[3]][,e]), main = length(temp[temp>CNV_overview[[3]][e]])/200)
abline(v = CNV_overview[[3]][e], col = "red")
heatmap[3,e] <- 1-(length(temp[temp>CNV_overview[[3]][e]])/200)
}  

```

```{r}
e <- 1
for (e in 1:11) {
temp <- run_overview[[4]][,e]
plot(density(run_overview[[4]][,e]), main = length(temp[temp>CNV_overview[[4]][e]])/200)
abline(v = CNV_overview[[4]][e], col = "red")
heatmap[4,e] <- 1-(length(temp[temp>CNV_overview[[4]][e]])/200)
} 
```



```{r}
heatmap(heatmap[1:4,], Colv = NA, Rowv = NA, scale="none", col = cm.colors(20))
x <- 1:13
lo <- loess(heatmap[1,1:13]~x)
plot(heatmap[1,1:11], ylab = "1-p", xlab = "developmental period" , main = "V1C - ITC - IPC - A1C - STC")
abline(h = 0.95, col = "red")
abline(h = 0.9, col = "orange")
lines(predict(lo), col='red', lwd=2)



x <- 1:17
lo <- loess(heatmap[2,]~x)
plot(heatmap[2,], ylab = "1-p", xlab = "developmental period" , main = "DFC - VFC - MFC - OFC - S1C - M1C - M1C-S1C")
abline(h = 0.95, col = "red")
abline(h = 0.9, col = "orange")
lines(predict(lo), col='red', lwd=2)

x <- 1:11
lo <- loess(heatmap[3,1:11]~x)
plot(heatmap[3,1:11], ylab = "1-p", xlab = "developmental period" , main = "STR - HIP - AMY")
abline(h = 0.95, col = "red")
abline(h = 0.9, col = "orange")
lines(predict(lo), col='red', lwd=2)

x <- 1:11
lo <- loess(heatmap[4,1:11]~x)
plot(heatmap[4,1:11], ylab = "1-p", xlab = "developmental period" , main = "MD - CBC")
abline(h = 0.95, col = "red")
abline(h = 0.9, col = "orange")
lines(predict(lo), col='red', lwd=2)
```

