---
title: "Network strength by gene permutation"
output: html_notebook
---

```{r}
setwd("C:/Users/Wietse/Desktop/Stage/Current work file")
library(tidyverse)
library(WGCNA)
library(AnnotationDbi)
library(igraph)
library(gdata)

options(stringsAsFactors = TRUE)
expression_data <- read.csv("expression_matrix.csv", header = FALSE)
column_data <- read.csv("columns_metadata.csv")
row_data <- read.csv("rows_metadata.csv")

expression_data <- expression_data[-1];
rownames(expression_data) <- row_data[,3]
expression_data$entrez_id <- row_data[,5]
expression_data <- expression_data[!is.na(expression_data$entrez_id), ]

row_data <- row_data[!is.na(row_data$entrez_id), ]

expression_data<- expression_data[ , -which(names(expression_data) %in% c("entrez_id"))]

expression_data.t <- t(expression_data)
expression_data.t <- as.data.frame(expression_data.t)

rownames(expression_data.t) <- paste0("S", 1:nrow(expression_data.t))
rownames(column_data) <- paste0("S", 1:nrow(column_data))

expression_data.t<- log2(expression_data.t + 1)

gsg <- goodSamplesGenes(expression_data.t)
expression_data.t = expression_data.t[gsg$goodSamples, gsg$goodGenes]
row_data = row_data[gsg$goodGenes,]
```

```{r}
CNV_genes <- c(
"ENSG00000013364", "ENSG00000072864", "ENSG00000079616",
"ENSG00000085721", "ENSG00000090238", "ENSG00000091262",
"ENSG00000102879", "ENSG00000102882", "ENSG00000102886",
"ENSG00000103222", "ENSG00000103485", "ENSG00000103495",
"ENSG00000103502", "ENSG00000103512", "ENSG00000133392",
"ENSG00000133393", "ENSG00000149922", "ENSG00000149923",
"ENSG00000149925", "ENSG00000149926", "ENSG00000149929",
"ENSG00000149930", "ENSG00000149932", "ENSG00000156968",
"ENSG00000157045", "ENSG00000166780", "ENSG00000166783",
"ENSG00000167194", "ENSG00000167371", "ENSG00000169592",
"ENSG00000174938", "ENSG00000174939", "ENSG00000174943",
"ENSG00000183336", "ENSG00000183793", "ENSG00000197471",
"ENSG00000254852"
)

gene_names <- subset(row_data, ensembl_gene_id %in% CNV_genes)
expression_data_CNV_genes <- as.data.frame(t(t(expression_data.t)[ which(row_data$ensembl_gene_id %in% CNV_genes),]))

expression_data.full <- as.data.frame(t(t(expression_data.t)[ -which(row_data$ensembl_gene_id %in% CNV_genes),]))
row_data.full <- row_data[ -which(row_data$ensembl_gene_id %in% CNV_genes),]
column_data.full <- column_data

```

```{r}
CNV_overview <- list(matrix(c(0), nrow = 1, ncol = 13),matrix(c(0), nrow = 1, ncol = 17),matrix(c(0), nrow = 1, ncol = 11), matrix(c(0), nrow = 1, ncol = 11))

a<-1

for (a in 1:4) {
  
 if(a == 1){
  expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in% c("V1C","ITC","IPC","A1C","STC"),]
  column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("V1C","ITC","IPC","A1C","STC"),]
 
  from_options <- c(1,3,17,31,45,49,53,58,63,64,66,71,82,86,91)
  to_options <- c(2,16,30,44,48,52,57,62,63,65,70,81,85,90,94)
  }
 if(a == 2){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
  
    from_options <- c(1,6,10,27,45,59,64,68,74,80,81,82,88,99,103,109,114,122,124)
    to_options <- c(5,9,26,44,58,63,67,73,79,80,81,87,98,102,108,113,121,123,132)
 }
  if(a == 3){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("STR","HIP","AMY"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("STR","HIP","AMY"),]
  
    from_options <- c(1,3,5,14,23,30,33,35,38,41,44,51,54)
    to_options <- c(2,4,13,22,29,32,34,37,40,43,50,53,54)
  }
  if(a == 4){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("MD","CBC"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("MD","CBC"),]
  
    from_options <- c(1,2,3,7,9,10,12,14,15,17,21,23,25)
    to_options <- c(1,2,6,8,9,11,13,14,16,20,22,24,26)
  }
 b<-1 

for (b in 1:(length(from_options)-2)) {
    from<- from_options[b]
    j = b + 2
    to <- to_options[j]
    
    expression_data.t<- expression_data.t1[from:to, ]
    column_data <- column_data1[from:to, ]

    
    annot <- gene_names
    rownames(annot) <- paste0(1:nrow(annot))
    annot <- rowid_to_column(annot)
    nodes <- annot[,-c(2:4, 6:7)]
    
    adjacency <- adjacency(expression_data.t, type = "signed")

    TOM_per <- TOMsimilarity(adjacency, TOMType = "signed")
    rownames(TOM_per) = rownames(adjacency)
    TOM_per <- t(TOM_per)
    rownames(TOM_per) = rownames(adjacency)

    vis = exportNetworkToVisANT(TOM_per,
    file = NULL,
    weighted = TRUE,
    threshold = 0.25,
    probeToGene = data.frame(annot$ensembl_gene_id, annot$gene_symbol))
    vis <- vis[,-c(3:4)] 

    edges <- vis %>% 
    left_join(nodes, by = c("from" = "gene_symbol")) %>% 
    dplyr::rename(from1 = rowid)
    edges <- edges %>% 
    left_join(nodes, by = c("to" = "gene_symbol")) %>% 
    dplyr::rename(to1 = rowid)
    edges <- dplyr::select(edges, from1, to1, weight)

    graph <- graph_from_data_frame(d = edges, vertices = nodes, directed = FALSE)

    degree_centrality <- centr_degree(graph, normalized = FALSE)



CNV_overview[[a]][1,b] <- centralize(degree_centrality[["res"]], theoretical.max = degree_centrality[["theoretical_max"]], normalized = TRUE)
}
}
```

```{r}

run_overview <- list(matrix(c(0), nrow = 37, ncol = 13), matrix(c(0), nrow = 37, ncol = 17), matrix(c(0), nrow = 37, ncol = 11),matrix(c(0), nrow = 37, ncol = 11) )

a <- 1

for (a in 1:4) {
  
 if(a == 1){
  expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in% c("V1C","ITC","IPC","A1C","STC"),]
  column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("V1C","ITC","IPC","A1C","STC"),]
 
  from_options <- c(1,3,17,31,45,49,53,58,63,64,66,71,82,86,91)
  to_options <- c(2,16,30,44,48,52,57,62,63,65,70,81,85,90,94)
  }
 if(a == 2){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("DFC","VFC","MFC","OFC","S1C","M1C","M1C-S1C"),]
  
    from_options <- c(1,6,10,27,45,59,64,68,74,80,81,82,88,99,103,109,114,122,124)
    to_options <- c(5,9,26,44,58,63,67,73,79,80,81,87,98,102,108,113,121,123,132)
 }
  if(a == 3){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("STR","HIP","AMY"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("STR","HIP","AMY"),]
  
    from_options <- c(1,3,5,14,23,30,33,35,38,41,44,51,54)
    to_options <- c(2,4,13,22,29,32,34,37,40,43,50,53,54)
  }
  if(a == 4){
    expression_data.t1 <- expression_data_CNV_genes[column_data.full$structure_acronym %in%  c("MD","CBC"),]
    column_data1 <- column_data.full[column_data.full$structure_acronym %in% c("MD","CBC"),]
  
    from_options <- c(1,2,3,7,9,10,12,14,15,17,21,23,25)
    to_options <- c(1,2,6,8,9,11,13,14,16,20,22,24,26)
  }

  b<-1 
  for (b in 1:(length(from_options)-2)) {
    from<- from_options[b]
    j = b + 2
    to <- to_options[j]
    
    expression_data.t<- expression_data.t1[from:to, ]
    column_data <- column_data1[from:to, ]
    c <- 1
for (c in 1:length(CNV_genes)) {
  
  expression_data.p <- expression_data.t[,-c]
  
  annot <- subset(row_data, row_data$ensembl_gene_id %in% names(expression_data.p))
  rownames(annot) <- paste0(1:nrow(annot))
  annot <- rowid_to_column(annot)
  nodes <- annot[,-c(2:4, 6:7)]
  
  
  
  adjacency <- adjacency(expression_data.p, type = "signed")

  TOM_per <- TOMsimilarity(adjacency, TOMType = "signed")
  rownames(TOM_per) = rownames(adjacency)
  TOM_per <- t(TOM_per)
  rownames(TOM_per) = rownames(adjacency)

  vis = exportNetworkToVisANT(TOM_per,
  file = NULL,
  weighted = TRUE,
  threshold = 0.25,
  probeToGene = data.frame(annot$ensembl_gene_id, annot$gene_symbol))
  vis <- vis[,-c(3:4)] 

edges <- vis %>% 
  left_join(nodes, by = c("from" = "gene_symbol")) %>% 
  dplyr::rename(from1 = rowid)
edges <- edges %>% 
  left_join(nodes, by = c("to" = "gene_symbol")) %>% 
  dplyr::rename(to1 = rowid)
edges <- dplyr::select(edges, from1, to1, weight)

graph <- graph_from_data_frame(d = edges, vertices = nodes, directed = FALSE)

degree_centrality <- centr_degree(graph, normalized = FALSE)

run_overview[[a]][c,b] <- centralize(degree_centrality[["res"]], theoretical.max = degree_centrality[["theoretical_max"]], normalized = TRUE)
}
  }
}
```

```{r}

final_run_overview <- list(matrix(c(0), nrow = 37, ncol = 13), matrix(c(0), nrow = 37, ncol = 17), matrix(c(0), nrow = 37, ncol = 11),matrix(c(0), nrow = 37, ncol = 11) )

a <- 1
for (a in 1:4) {
  b <- 1
  for (b in 1:ncol(run_overview[[a]])) {
    c <- 1
    for (c in 1:37) {
      final_run_overview[[a]][c,b] <- run_overview [[a]][c,b] - CNV_overview[[a]][1,b]
    }
  }
}

plot(final_run_overview[[2]][,4])
text(final_run_overview[[2]][,4], labels = colnames(overall_scores), cex = 0.7, pos=3)
abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")
plot(final_run_overview[[2]][,5])
text(final_run_overview[[2]][,5], labels = colnames(overall_scores), cex = 0.7, pos=3)
abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")
plot(final_run_overview[[2]][,6])
text(final_run_overview[[2]][,6], labels = colnames(overall_scores), cex = 0.7, pos=3)
abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")
plot(final_run_overview[[2]][,7])
text(final_run_overview[[2]][,7], labels = colnames(overall_scores), cex = 0.7, pos=3)
abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")


plot(final_run_overview[[1]][6,], main = "V1C - ITC - IPC - A1C - STC")
abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")
plot(final_run_overview[[2]][6,], main = "DFC - VFC - MFC - OFC - S1C - M1C - M1C-S1C")
abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")
plot(final_run_overview[[3]][6,], main = "STR - HIP - AMY")
abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")
plot(final_run_overview[[4]][6,], main = "MD - CBC")
abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")

overall_scores <- matrix(c(0), nrow = 4, ncol = 37)

a <- 1
for (a in 1:4) {
  b <- 1
for (b in 1:37) {
  overall_scores[a,b] <- mean(final_run_overview[[a]][b,])
}
}

annot <- subset(row_data, row_data$ensembl_gene_id %in% names(expression_data.t))
  rownames(annot) <- paste0(1:nrow(annot))
  annot <- rowid_to_column(annot)

colnames(overall_scores) <- annot$gene_symbol

plot(overall_scores[1,], main = "V1C - ITC - IPC - A1C - STC")
 text(overall_scores[1,], labels = colnames(overall_scores), cex = 0.7, pos=3)
 abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")

plot(overall_scores[2,], main = "DFC - VFC - MFC - OFC - S1C - M1C - M1C-S1C")
  text(overall_scores[2,], labels = colnames(overall_scores), cex = 0.7, pos=3)
   abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")

plot(overall_scores[3,], main = "STR - HIP - AMY")
  text(overall_scores[3,], labels = colnames(overall_scores), cex = 0.7, pos=3)
   abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")

plot(overall_scores[4,], main = "MD - CBC")
  text(overall_scores[4,], labels = colnames(overall_scores), cex = 0.7, pos=3)
 abline(h = -0.010, col = "orange")
 abline(h = -0.015, col = "red")





```

